### ISSUE TITLE
Persistent storage. 

### ISSUE THREAD

**Issue by ashish235** [jpmorganchase/quorum-cloud#9]
Hi, 

Deployed the Quorum on AWS and it works like a charm. The thing which I am not able to grasp is the nodes are deployed on Fargate which doesn't have any persistent storage. So this installation of quorum doesn't persist any data on disk? How do they recover if a container crashes? 
Thanks. 

Regards,
Ashish

**Comment by trung** [comment]
Hi, this setup is meant to be simple and doesn't cover different scenarios in a proper network deployment. 
I'm afraid in order to support recovery using Fargate, we need to find solutions for the below limitations:
1. [Fargate task storage is ephemeral](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html)
1. IP changes once a container is restarted
1. Coordination logic only supports network bootstrapping

Fargate might not be the best option when you want to have more controls on the network.

**Comment by fixanoid** [comment]
Please reopen if there are additional questions.
